### ISSUE TITLE
Error at key generation step

### ISSUE THREAD

**Issue by rahmas36** [ramin-ali-marandi-ghoddousi/SCAMPR#1]
Hi, I have been trying to run the SCAMPR program on the provided sample data. I created cellular masks with the HuCD tif file in the tissue section 2 (20-26~s1-Sec2) folder. I converted the masks to ImageJ ROIs and I am now trying to generate the key file for gene expression analysis of the 12 genes in the folder. I received a macro error message, which I attached as a screenshot. What does it mean?

<img width="561" alt="Screen Shot 2022-08-11 at 5 14 51 PM" src="https://user-images.githubusercontent.com/55713573/184245360-861b3611-5700-46a1-9756-36b8d57b936e.png">

**Comment by ramin-ali-marandi-ghoddousi** [comment]
Hi.  

You get this error when running the "SCAMPR_AreaFraction.ijm" macro and not during key file generation, correct?

The error that you screenshotted usually comes up when you choose the image subfolder (in this case "20-26.~s1-Sec2") instead of the folder containing all of the image subfolders ("Images" in the sample data).  Try putting the 20-26.~s1-Sec2 folder into another folder named "Images" (or whatever you want) and running the macro again.  When it asks you to select the folder that contains the images, select the "Images" folder.

**Comment by rahmas36** [comment]
Hi, I actually put the "20-26.~s1-Sec2" folder into another folder, and selected that folder. The error message pops after the key file is generated and there is a popup mentioning the particle size. 

<img width="794" alt="Screen Shot 2022-08-12 at 11 06 09 AM" src="https://user-images.githubusercontent.com/55713573/184385653-53efa058-c5f0-4945-b241-463303b54e39.png">

I just went with the default size of 1 and clicked ok. But even when I manually edited the particle size after zooming into a few spots on FiJI for every image I still received the error message.

**Comment by rahmas36** [comment]
I was using "SCAMPR_AreaFraction_SemiAuto.ijm"

**Comment by ramin-ali-marandi-ghoddousi** [comment]
Okay, I see.  The macro performs string manipulations on the image titles to get sample information and run properly.  This error seems to be related to that.  Can you please send screenshots of the images in 20-26~s1-Sec2, the ROI subfolders in your ROIs folder, a screenshot of the Key.csv file, and a screenshot of how you have your images and ROIs organized in folders and subfolders?

**Comment by rahmas36** [comment]
Hi, I attached the screenshots of the images and the folders. Previously, I did not have my ROIs in a subfolder, but now I do. Nonetheless, I still received the same error message.

<img width="631" alt="Screen Shot 2022-08-12 at 2 00 19 PM" src="https://user-images.githubusercontent.com/55713573/184417361-c4a8b14d-41a3-4880-8b40-c8272959bdc3.png">
<img width="631" alt="Screen Shot 2022-08-12 at 1 59 48 PM" src="https://user-images.githubusercontent.com/55713573/184417363-18fde255-e83e-4599-b1f5-a0cb1666e675.png">
<img width="633" alt="Screen Shot 2022-08-12 at 1 58 29 PM" src="https://user-images.githubusercontent.com/55713573/184417366-0e4f433a-ef97-4a94-afc8-010a29a0df85.png">
<img width="636" alt="Screen Shot 2022-08-12 at 1 57 50 PM" src="https://user-images.githubusercontent.com/55713573/184417368-27a639a7-908a-4212-b6c1-498cd182a9db.png">
<img width="648" alt="Screen Shot 2022-08-12 at 1 56 23 PM" src="https://user-images.githubusercontent.com/55713573/184417370-336e7a4c-d27e-42bb-920f-a40aa18a2d92.png">
<img width="642" alt="Screen Shot 2022-08-12 at 1 55 49 PM" src="https://user-images.githubusercontent.com/55713573/184417373-01642187-2c26-4e3a-9379-49567b01cf24.png">
<img width="642" alt="Screen Shot 2022-08-12 at 1 54 41 PM" src="https://user-images.githubusercontent.com/55713573/184417375-326be37d-13ac-43e3-b61c-ce49cad242b3.png">
<img width="649" alt="Screen Shot 2022-08-12 at 1 54 06 PM" src="https://user-images.githubusercontent.com/55713573/184417376-7b50dbb3-7357-4e5e-ae87-78ff313c84a4.png">
<img width="630" alt="Screen Shot 2022-08-12 at 1 53 28 PM" src="https://user-images.githubusercontent.com/55713573/184417377-0a31b391-e156-4aa0-b564-f7e4dd402bee.png">
<img width="630" alt="Screen Shot 2022-08-12 at 1 52 54 PM" src="https://user-images.githubusercontent.com/55713573/184417378-22a20575-9f7b-4766-bb27-b23fcbeaf4d1.png">
<img width="625" alt="Screen Shot 2022-08-12 at 1 51 59 PM" src="https://user-images.githubusercontent.com/55713573/184417380-9fd1ac5c-999a-4ac2-9ac6-d34942b1eaf8.png">
<img width="628" alt="Screen Shot 2022-08-12 at 1 51 19 PM" src="https://user-images.githubusercontent.com/55713573/184417381-9202853a-eabf-4dba-9aa0-252a1762554a.png">
<img width="627" alt="Screen Shot 2022-08-12 at 1 42 44 PM" src="https://user-images.githubusercontent.com/55713573/184417382-e7f5b29f-8b24-40dc-9e3f-d20e4fd20993.png">
<img width="776" alt="Screen Shot 2022-08-12 at 1 41 07 PM" src="https://user-images.githubusercontent.com/55713573/184417384-78b110fd-b445-49f2-8717-5e07f512d91d.png">
<img width="743" alt="Screen Shot 2022-08-12 at 1 39 24 PM" src="https://user-images.githubusercontent.com/55713573/184417385-6516c4b5-79e5-493f-945b-3807984687ea.png">

**Comment by ramin-ali-marandi-ghoddousi** [comment]
Thanks.  The error is due to your image titles.  Your image files need to be titled according to certain naming conventions to partially match the image subfolder.  I added a step (step 8) to the Image Registration section of the instructions to emphasize this.  You can look at the bottom of section 1 and the "Sample Data" folder to see examples of these naming conventions.  Let me know if you still run into issues after renaming your images.

**Comment by rahmas36** [comment]
Hi, I was able to obtain the area division and fraction summaries for the genes. I added the image sub-folder title to the beginning of every image file and zipped all the ROIs and put them into the ROI folder. Thanks!

**Comment by ramin-ali-marandi-ghoddousi** [comment]
Great!
