### ISSUE TITLE
slides registration and cell segmentation following the steps

### ISSUE THREAD

**Issue by KH201301** [ramin-ali-marandi-ghoddousi/SCAMPR#2]
Hi, cool pipeline for multiplexed images analysis. Tried follow the process steps provided. Have some questions hope can be solved here using this platform. 
1. I found the registration using image J-registration and tranformation tool (geuss all automaticlly), still can notice the align is not perfectly overlayed. Do you think I can use this platform instead ?"https://c4science.ch/w/warpy/"  Because this is semiautomated, we can adjust it if found not aligned 100%. But not sure the generated files can be processed for cell segmenation using Cellpose?
2. Based on Cellpose usage, we can build a better and accurate segmentation using 2 channels (DAPI+Cyto), for example, I add one cell surface marker to the DAPI channel (so merged DAPI and surface marker channel to make a stack and then generate tif, for segmenation in CellPose. So not sure how is this possible to do this? Based on the protocol, use DAPI images for each sample, run cellpose. Can I use merged DAPI+surface maker images for cell segmentation and generare ROIs? 
3. When it said Key file means 2 .CVS files named "NodoseAreaFraction" and "VisualCortexAreaFraction", loos like the following visualization and analysis mainly use "gene X cell count matrix", is this the file " VisualCortexAreaFraction"? Because I don't know what is the role on file "NodoseAreaFraction".
4. Can we follow those steps for multiplexed immunofluorescent staining images especially using the provided R script ?
Thanks very much!

Best,

Kun

**Comment by KH201301** [comment]
Dear Author, I am 0 experienced R script usage. Is that possible for you to make a video showing how to use the R script for visualization and analysis? Sorry, very eager to make it work using this pipeline!

**Comment by ramin-ali-marandi-ghoddousi** [comment]
> Hi, cool pipeline for multiplexed images analysis. Tried follow the process steps provided. Have some questions hope can be solved here using this platform.
> 
> 1. I found the registration using image J-registration and tranformation tool (geuss all automaticlly), still can notice the align is not perfectly overlayed. Do you think I can use this platform instead ?"https://c4science.ch/w/warpy/"  Because this is semiautomated, we can adjust it if found not aligned 100%. But not sure the generated files can be processed for cell segmenation using Cellpose?
> 2. Based on Cellpose usage, we can build a better and accurate segmentation using 2 channels (DAPI+Cyto), for example, I add one cell surface marker to the DAPI channel (so merged DAPI and surface marker channel to make a stack and then generate tif, for segmenation in CellPose. So not sure how is this possible to do this? Based on the protocol, use DAPI images for each sample, run cellpose. Can I use merged DAPI+surface maker images for cell segmentation and generare ROIs?
> 3. When it said Key file means 2 .CVS files named "NodoseAreaFraction" and "VisualCortexAreaFraction", loos like the following visualization and analysis mainly use "gene X cell count matrix", is this the file " VisualCortexAreaFraction"? Because I don't know what is the role on file "NodoseAreaFraction".
> 4. Can we follow those steps for multiplexed immunofluorescent staining images especially using the provided R script ?
>    Thanks very much!
> 
> Best,
> 
> Kun

Hi Kun

1. You can try changing the feature extraction and registration models in step 4 of the instructions to see if that helps with the alignment.  You can use any other program to perform the registration, as long as the output is a TIFF image file.
2. You can try and create a combined RGB image with the DAPI+marker prior to segmentation but depending on your cell/tissue type and packing density it may not help and may even make things worst.  You can set corresponding marker and DAPI channels in step 4 of the Cellpose2DSegmentation colab notebook.
3.  The VisualCortexAreaFraction and NodoseAreaFraction files are those that were generated for the publication and are provided for reference.  You can use the Gene X Cell Count Matrix created from Step 4 and the ROIs created from from Step 3 to run the R analysis scripts.
4.  As long as you have ROI files and some kind of Gene X Cell Count Matrix file that contains expression information, you should be be able to use the R scripts for analysis.

**Comment by ramin-ali-marandi-ghoddousi** [comment]
> Dear Author, I am 0 experienced R script usage. Is that possible for you to make a video showing how to use the R script for visualization and analysis? Sorry, very eager to make it work using this pipeline!

At this point we do not have any plans to make instructional videos.  Once you have generated the gene by cell matrix in step 4, you can use it in conjunction with the ROIs to run through the R scripts.  The scripts are well annotated and should be easy to follow along step-by-step.  If you run into particular issues leave a comment or question and I will be happy to help.
