### ISSUE TITLE
gene expression quanfication in semiautomated manner

### ISSUE THREAD

**Issue by KH201301** [ramin-ali-marandi-ghoddousi/SCAMPR#3]
Hi, Ramin,

I was stucked in the step for gene expression quanfication in semiautomated manner using "semiauto.ijm" script, not sue the sentence "SCAMPR allows for the option of estimating the number of particles in each cell by dividing the number of pixels by an anverage pariticle size (is this a canculator?)". I can find the key.csv file, and can see corrected threshold and average particle size (all 1 by default). 

1. A "action required" window come out, and it said note the image-specific particle size", but in this step I cannot open the image in ImageJ. must I close this R script, and then open the image to get the value?
2. how can I get the average the number of pixels by removing background and threshold using corrected threshold in the Key.CSV? hen it said "average the number of pixels comprising the spots, input this number into Key file", but I can only see"Mean	logMeans", "CorrectionFactor", "Corrected Threshold", and  "Average Particle Size", where I type "number of pixels"? should I canculate the "Average Particle Size" here from each image of the channel?

Thanks very much!!!

Kun

**Comment by ramin-ali-marandi-ghoddousi** [comment]
Hi Kun,

1.   You can open a **new** imageJ window to open each image, calculate the average particle size, and change the default value in the key.
2. You have to calculate the average number of pixels yourself by opening each image, performing background removal and thresholding using the "corrected threshold" value for that image in the key, picking 2-3 spots at random, counting how many pixels are in each spot (either visually, or by outlining the spot using the freehand selection tool and hitting "m" on your keyboard), and averaging those counts to get the average particle size.

Best,
Ramin

**Comment by KH201301** [comment]
> 

Hi, Ramin,

Thanks so much on this. OK, will we keep all different rounds of DAPI flattened image in the image folder when run :SCAMPR_AreaFraction_SemiAuto.ijm" to generate ROIs? I found if I put DAPI in the folder, it awlays select DAPI as representative image to threshold. 
And I always met this erro, is this matter? Because I can see the generated CVS files.


<img width="648" alt="image" src="https://user-images.githubusercontent.com/113857936/192077356-10bfefff-675d-4011-80bf-8f07e798eff7.png">

<img width="432" alt="image" src="https://user-images.githubusercontent.com/113857936/192077381-d30d1f59-849d-4d0f-ae1e-071a0fa78ba4.png">

**Comment by KH201301** [comment]
> Hi Kun,
> 
> 1. You can open a **new** imageJ window to open each image, calculate the average particle size, and change the default value in the key.
> 2. You have to calculate the average number of pixels yourself by opening each image, performing background removal and thresholding using the "corrected threshold" value for that image in the key, picking 2-3 spots at random, counting how many pixels are in each spot (either visually, or by outlining the spot using the freehand selection tool and hitting "m" on your keyboard), and averaging those counts to get the average particle size.
> 
> Best, Ramin

And I think if I make changes on "Average Particle Size" in Key, and have this erro, I get no "(ThresArea / PartArea) Count" in the generated fils. 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/113857936/192078308-bef239a2-e20f-44c1-8b34-480aca1790d2.png">

<img width="382" alt="image" src="https://user-images.githubusercontent.com/113857936/192078317-1f8e10b4-1ab0-438a-bab8-d8f69730435d.png">

**Comment by KH201301** [comment]
Sorry, and this erro. 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/113857936/192078426-e0d9415b-1e79-47fb-8e84-3745b79037f4.png">

**Comment by ramin-ali-marandi-ghoddousi** [comment]
> > 
> 
> Hi, Ramin,
> 
> Thanks so much on this. OK, will we keep all different rounds of DAPI flattened image in the image folder when run :SCAMPR_AreaFraction_SemiAuto.ijm" to generate ROIs? I found if I put DAPI in the folder, it awlays select DAPI as representative image to threshold. And I always met this erro, is this matter? Because I can see the generated CVS files.
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/113857936/192077356-10bfefff-675d-4011-80bf-8f07e798eff7.png">
> 
> <img alt="image" width="432" src="https://user-images.githubusercontent.com/113857936/192077381-d30d1f59-849d-4d0f-ae1e-071a0fa78ba4.png">

You should definitely pull out the DAPI images and any other non-mRNA images from your folder before running the SCAMPR_AreaFraction_SemiAuto.ijm macro.  The macro uses your "brightest" image as an anchor point so that's why you keep getting a DAPI image as representative.

The error is a separate issue and likely has to do with the organization of your files.  Your image subforder(s) need to be placed in a main images folder.  This main images folder is the one that you select when you run the macro.  Please take a look at the Sample Data for examples of this organization.

**Comment by ramin-ali-marandi-ghoddousi** [comment]
I also wanted to point out that your manually determined threshold (500) is way out of the range of possible thresholds.  This number should be between 0 and 255.
