### ISSUE TITLE
script error "SCAMPR_AreaFraction_SemiAuto.ijm"

### ISSUE THREAD

**Issue by KH201301** [ramin-ali-marandi-ghoddousi/SCAMPR#4]
Hi, Ramin,
Thanks so much on this.
OK, will we keep all different rounds of DAPI flattened image in the image folder when run :SCAMPR_AreaFraction_SemiAuto.ijm" to generate ROIs? I found if I put DAPI in the folder, it awlays select DAPI as representative image to threshold.
And I always met this erro, is this matter? Because I can see the generated CVS files.
And I think if I make changes on "Average Particle Size" in Key, and have this erro, I get no "(ThresArea / PartArea) Count" in the generated fils.
errors below.
![image](https://user-images.githubusercontent.com/113857936/192112303-316b5e0e-a7a4-49db-b943-7e4e2241ccf3.png)
![image](https://user-images.githubusercontent.com/113857936/192112307-6a7475af-03d0-4eb5-b014-49d399a83613.png)
![image](https://user-images.githubusercontent.com/113857936/192112314-a36a568e-1c46-4b93-8b50-137952e81303.png)
![image](https://user-images.githubusercontent.com/113857936/192112321-50749249-344e-402d-a858-06a49a1837ce.png)
![image](https://user-images.githubusercontent.com/113857936/192112323-af2627cb-f767-40e9-98f6-2957359ae9cd.png)

**Comment by ramin-ali-marandi-ghoddousi** [comment]
Duplicate
