### ISSUE TITLE
Mannual gene expresion quantification steps

### ISSUE THREAD

**Issue by KH201301** [ramin-ali-marandi-ghoddousi/SCAMPR#5]
Hi, Dear Ramin,

I also tried mannual gene expresion quantification step. I can run and generate a template CVS fils running R script in RStudio. 
However, I alwway met the same issue below after click run and areafraction.ijm in ImageJ:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/113857936/192347886-e6d8a008-3c16-4b07-a67c-ecb22379167f.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/113857936/192347965-e70c683d-4cab-48d0-8a7c-1d3b691aa561.png">
Here is my folder, the gray hilighted is the image folder, also ROIs, results, and Key fils. 
<img width="649" alt="image" src="https://user-images.githubusercontent.com/113857936/192348289-26e6c818-dda2-4983-b874-d638990d8447.png">

Thank you so much on this!!! 

Kun

**Comment by ramin-ali-marandi-ghoddousi** [comment]
Hi Kun,

Please place your image folder (2-1~s1-Sec13) into a seperate folder (named "Images" or whatever else).  Select this folder and not when you run the macro.

I highly suggest running the macros on the Sample Data first.  When you're familiar with the process, organize your images and folders using the Sample Data as a guide and then run the code.

Best,
Ramin
